version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus/volume:/prometheus
    ports:
      - 9090:9090
    command:
      - '--web.enable-lifecycle'  # Allows you to reload configuration files without restarting api
      - '--config.file=/etc/prometheus/prometheus.yaml'
    restart: always